### ISSUE TITLE
UI broken on fresh install - Cannot find module "../elements/DeployButton.component"

### ISSUE THREAD

**Issue by esmevane** [supergiant/supergiant-dashboard#110]
In https://github.com/supergiant/supergiant/issues/74, @mike503 wrote:

>Fresh install today, on AWS, using `bash <(curl -L https://supergiant.io/installer)`

>Went to the Super Giant Dashboard URL: http://supergiant-supergiant-REMOVED.us-east-1.elb.amazonaws.com:30048

> (removed my specific ELB address for privacy)

> Due to this error, the UI won't show anything.

> `Releases.component.js:27 Uncaught Error: Cannot find module  "../elements/DeployButton.component"webpackMissingModule @ Releases.component.js:27(anonymous function) @ Releases.component.js:27(anonymous function) @ Releases.component.js:172(anonymous function) @ application.js:57n @ application.js:1(anonymous function) @ Releases.container.js:21(anonymous function) @ Releases.container.js:112(anonymous function) @ application.js:57n @ application.js:1(anonymous function) @ routes.js:51(anonymous function) @ routes.js:124(anonymous function) @ application.js:35n @ application.js:1(anonymous function) @ index.js:19(anonymous function) @ index.js:54(anonymous function) @ application.js:2n @ application.js:1(anonymous function) @ multi_main:2(anonymous function) @ application.js:1n @ application.js:1(anonymous function) @ application.js:1(anonymous function) @ application.js:1`

**Comment by esmevane** [comment]
It seems like this has to do with a container script build error.  Attempting to duplicate locally right now.

**Comment by esmevane** [comment]
Looks like a locally conducted production build / serve of the dashboard doesn't have this issue.  @mike503 - do you have any more environment information you can give us?

**Comment by mike503** [comment]
sure, what information do you want?

**Comment by esmevane** [comment]
Actually, let me backpedal a bit - could you try this when you have a minute:

```bash
supergiant delete core && supergiant create core
```

That will attempt a reinstall. It looks like we had a dashboard build out yesterday which may have had this problem, so there's a chance that a build released this afternoon may have fixed it.

**Comment by mike503** [comment]
firstly, doesn't look like the cluster was ready the first time. second "create core" worked, but the same UI issue persists.

`local$ supergiant delete core && supergiant create core
Core delete Success...
Kube context is: supergiant
WARN: Namespace exists.
INFO: AWS Credentials Installed From Provider DB.
Creating ETCD Data Volume.
WARN: ETCD exists.
WARN: ETCD BROWSER exists.
WARN: ETCD BROWSER exists. Resource not found
Waiting for core to settle... This can take a few minutes.
? Core Install failed:  Supergiant API Install Failed.

local$ supergiant create core
Kube context is: supergiant
&{0x18b72720 0x18bbed80 0x18beaa80}
INFO: AWS Credentials Installed From Provider DB.
Creating ETCD Data Volume.
Waiting for core to settle... This can take a few minutes.
Supergiant API verified...
APP: supergiant
Waiting port detect...
Port detected...
Waiting Dashboard to be active...
Dashboard Detected...
Dashboard URL: http://supergiant-supergiant-123.us-east-1.elb.amazonaws.com:31303
Core install Success...`

**Comment by esmevane** [comment]
Okay!  Sorry about all of this, but _thank you so much_ for the issue and help.  I have a new build rolling out now which fixes the problem (possibly the most embarrassing problem ever - file capitalization).

**Comment by esmevane** [comment]
Just wanted to revisit this and say I've confirmed the new build doesn't have the error - thanks again :)

**Comment by mike503** [comment]
verified
