### ISSUE TITLE
Components appear duplicated across Apps sharing same base name

### ISSUE THREAD

**Issue by FestivalBobcats** [supergiant/supergiant-dashboard#123]
I have 2 apps, one named **test** and the other **test-2**. When I create a new Component in **test-2**, it shows up under the **test** App as well.

I've confirmed that the Components are not actually duplicated at the API level, so it appears to be a display bug of some kind.

<img width="770" alt="screen shot 2016-05-18 at 11 10 55 am" src="https://cloud.githubusercontent.com/assets/251029/15369999/d6604446-1ce9-11e6-8acf-f845757878f7.png">

**Comment by esmevane** [comment]
Ok, I've got reproduction locally - 
![jceavdfath](https://cloud.githubusercontent.com/assets/263460/15373488/87652be6-1d0b-11e6-9081-cae4ed02d8c2.gif)

**Comment by briansage** [comment]
Fixed in #125
