### ISSUE TITLE
When increasing instance count for a component, the instance count in cube just stays the same. 

### ISSUE THREAD

**Issue by gopherstein** [supergiant/supergiant-dashboard#126]
The api does not appear to have been told to increase the instance count to anything higher. 

```time="2016-05-19T15:22:58Z" level=info msg="Starting Task start : /apps/my-website/components/mongo-cluster/releases/20160519152252/instances/0"
time="2016-05-19T15:22:58Z" level=info msg="Creating ReplicationController mongo-cluster-020160519152252"
time="2016-05-19T15:22:58Z" level=info msg="Waiting for ReplicationController mongo-cluster-020160519152252 to start"```

**Comment by esmevane** [comment]
Hey @gopherstein - I mentioned this to you in messages a few weeks back but I think it bears reiteration here for anyone who's looking.  This is an API error.  The Dashboard is submitting the right instance count and the release API is responding with 1.
