### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by jalaluddeen** [supergiant/supergiant-dashboard#128]
Hi, I am getting the below dependency error when I run  " npm install && npm run build" , 

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.5
npm ERR! npm  v2.15.5
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-dom@15.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer redux-slider-monitor@1.0.5 wants react-dom@^0.14.0 || ^15.0.0
npm ERR! peerinvalid Peer react-input-color@1.7.2 wants react-dom@^0.14.0

**Comment by esmevane** [comment]
Hey @jalaluddeen - Thanks for the heads up.  I've got the issue, but the fix seems to be to just move beyond the react input color support.  Got a fix headed upstream soon.

**Comment by esmevane** [comment]
Okay!  The newest version of the dashboard, [0.5.18](https://github.com/supergiant/supergiant-dashboard/releases/tag/v0.5.18), shouldn't have this peer dependency problem.

**Comment by jalaluddeen** [comment]
Thank you! dependency error is fixed in the new version
