### ISSUE TITLE
Resolve DOM nesting errors on settings page.

### ISSUE THREAD

**Issue by esmevane** [supergiant/supergiant-dashboard#65]
It appears that there's some DOM nesting problems on the settings page (Entrypoints and Registries react components most likely).  I'm guessing React is trying to usher us into using `thead` and `tbody`.

<img width="1072" alt="screen shot 2016-04-20 at 9 01 51 am" src="https://cloud.githubusercontent.com/assets/263460/14677395/2fab332c-06d7-11e6-8525-9862f91db11d.png">

**Comment by esmevane** [comment]
Trello card here: https://trello.com/c/vSOTgGPH/21-resolve-dom-nesting-errors-on-settings-page

**Comment by briansage** [comment]
Fixed in #77
