### ISSUE TITLE
When a release is created users should remain on the Releases view

### ISSUE THREAD

**Issue by briansage** [supergiant/supergiant-dashboard#94]
## Bugged behavior:
As a Dashboard user on the Component Releases view, when I click to create a Release, I am redirected to the Dashboard.

## Expected Behavior
As a Dashboard user on the Component Releases view, when I click to create a Release, I should be shown the Component Releases view.

![Example recording](http://g.recordit.co/LvD1n0WeZw.gif)

**Comment by esmevane** [comment]
This was resolved by https://github.com/supergiant/supergiant-dashboard/pull/100
